spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

accounts:
  message: "Welcome to Accounts Microservice "
  contactDetails:
    name: "Rahul-Prodlead"
    email: "rahulsinghengnr@gmail.com"
  callSupport:
    -(555)555-1234
    -(555)523-1987
