spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to Accounts Microservice "
  contactDetails:
    name: "Reena-QAlead"
    email: "reenasingh123@gmail.com"
  callSupport:
    -(555)555-1234
    -(555)523-1987
