build:
  version: 3.0
cards:
  message: "Welcome to cards Microservice "
  contactDetails:
    name: "prateek"
    email: "prateeksinghengnr@gmail.com"
  callSupport:
    -(555)555-1234
    -(555)523-1987