build:
  version: "3.0"
loans:
  message: "Welcome to Loans  Microservice "
  contactDetails:
    name: "Devi default Lead"
    email: "devihengnr@gmail.com"
  callSupport:
    -(555)555-1234
    -(555)523-1987