spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/prateekDazz/Config-prateekdazz.git"
          default-label: main
          timeout: 5
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///C://Users//prate//OneDrive//Documents//config"


encrypt:
  key: "45GDJHUIR56BHSKO57FHSDLORHB098DJ"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

